// Store all translations
const translations = {
  en: {
    // Navigation
    "nav.about": "About ICPM",
    "nav.why": "Why UAE?",
    "nav.benefits": "Who Can Participate?",
    "nav.objective": "Objectives",
    "nav.future": "Future Plan",
    "nav.booths": "Booth Options",
    "nav.contact": "Contact",

    // Hero Section

    




    "hero.offer": "Exclusive Offer",
    "hero.companies": "Scandinavian companies receive a 5% discount through Keeada!",
    "hero.contact": "Contact us",
    "hero.claim": "to claim your discount.",
    "hero.title": "Take Your Healthcare Innovation to the Middle East",
    "hero.subtitle": "Exhibit at The 14ᵗʰ ICPM Conference 2026 in the UAE",
    "hero.text": "Join one of the Middle East's largest healthcare and pharmaceutical exhibitions.<br>January 20-22, 2026 — Sharjah Research Technology & Innovation Park, UAE.",
    "hero.apply": "Apply for Exhibitor Spot",
    "hero.download": "Download Brochure",
    "hero.call": "Schedule a Call",
    "timer.title": "TIME REMAINING",
    "timer.days": "DAYS",
    "timer.hours": "HOURS",
    "timer.minutes": "MINUTES",
    "timer.seconds": "SECONDS",

    // About Section
    "about.title": "What is ICPM?",
    "about.text1": "ICPM is a platform where it covers local and international market, you will have the exclusive chance to meet one on one with the key authorities and decision makers from all GCCand MENAcountries and overseas in healthcare sector.",
    "about.text2": "ICPM is covering Medical, Medical Tourism, Insurance, pharmacy education, Pharma industry , regulatory affairs, Bioequivalence studies, Pharmacovigilance, medicine pricing, dental laboratories, dental, diagnostic labs, and GMP department, genetics, Veterinary, Aesthetics, derma, beauty and cosmetics, accessibilities and rehabilitation.",
    "about.text3": "Moreover you will encounter leading industry experts, consultant , healthcare provider and CEO’s in the healthcare field in private sessions and B2B.",

    // Why UAE Section
    "why.title": "Why the UAE — and Why Now?",
    "why.text1": "Every year ICPM ties up with different success story, and after the success in last 13 events in UAE, this year ICPM is collaborating with government authority under one platform.",
    "why.text2": "Direction and Vision of UAE is to improve and provide the world class healthcare industry, The healthcare scope and gain the trust of healthcare authorities and healthcare providers.",
    "why.text3": "UAE’s economy has seen an unprecedented growth over the past few years which are the result of policies that investor friendly like cuttingred tape and expanding of economic and commerce in UAE considering its importance and the support extended from UAE Rulers, ICPM decided to take the opportunity and organize 14ᵗʰ edition of ICPM at UAE.",

    // Who Can Participate?
    "Who.title": " Who Can Participate?",
    "Who.text": "ICPM 2026 is ideal for companies and organizations in:",
    "Who.text1": "Pharmaceutical manufacturers and Biotech industries",
    "Who.text2": "Hospitals and Healthcare providers",
    "Who.text3": "Medical equipment companies and distributors",
    "Who.text4": "Medical disposable, consumable companies",
    "Who.text5": "Healthcare Consultant and Investors",
    "Who.text6": "Professors from Pharmaceutical/Biotech institutes",
    "Who.text7": "Universities and academicians",
    "Who.text8": "Assembling companies (Ambulance, Mobile Hospitals)",
    "Who.text9": "Health Insurance Companies",
    "Who.text10": "Healthcare Genetics Centers",
    "Who.text11": "Aesthetics, cosmetics and beauty companies",
    "Who.text12": "Healthcare Government agencies, Media and publication",
    "Who.text13": "Government offices and Municipalities",
    "Who.text14": "Veterinary Factories, companies and distributors",
    "Who.text15": "Drug distribution agencies and scientific offices",
    "Who.text16": "Hospitality, Hotels, Spa, Rehabilitation Companies",
    "Who.text17": "Non Profit Organization",
    "Who.text18": "Multivitamins, organics, herbal product manufacturers",
    "Who.text19": "Sports and Nutrition products manufacturers",
    "Who.text20": "Logistic, Import & Export Companies",
    "Who.text21": "Free Zone Authorities and storage facilities",

    // Purpose & Objectives of ICPM
    "Purpose.title": " Purpose & Objectives of ICPM",
    "Purpose.text1": " To promote a healthier lifestyle as well as to prevent lifestyle related diseases.",
    "Purpose.text2": " Connect the multinational pharmaceutical & medical companies, distributors and retailers with UAE & GCC Regulatory Authorities",
    "Purpose.text3": " To highlight the awareness about mass gathering medicine",
    "Purpose.text4": " Make a strong connection between the universities, manufacturers, distributors and retailers for the benefit of healthcare",
    "Purpose.text5": " Promote, support and Facilitate the Medical tourism in UAE",
    "Purpose.text6": " Provide world class treatment to patient with low cost",
    "Purpose.text7": " Consolidate efforts between scientific organizations and Healthcare Companies",
    "Purpose.text8": " Share the updated information on the latest technology",
    "Purpose.text9": " Promote new business and technology ideas in the healthcare sector",
    "Purpose.text10": " Make a strong connection between the Private and Government hospitals",
    "Purpose.text11": " To increase access to the decentralizing public health system by establishing new infrastructure in existing institutions",
    "Purpose.text12": " Developing the domestic pharmaceutical industries and hospitals",

    // Future Plan

    "Future.title": "Future Plan",
    "Future.text1": "Every year Keeada through ICPM will be collaborating with various reputed healthcare companies around UAE and around the world. As this will be the link between the scientists and professionals, all our ICPM events will be held in collaboration with the most reputable companies.",
    "Future.text2": "This initiative will uplift the healthcare field and result in the best outcomes from healthcare providers who are shaping the future of medicine.",
    "Future.title1": "Global Collaboration",
    "Future.text3": "Partnering with leading healthcare organizations worldwide",
    "Future.title2": "Strategic Partnerships",
    "Future.text4": "Building bridges between scientists and industry professionals",
    "Future.title3": "Sustainable Growth",
    "Future.text5": "Creating lasting impact in healthcare innovation",


    // Booth Options Section
    "Booth.title": "Booth Packages and Sponsorship Opportunities",
    "Booth.text": "Choose the size and visibility level that suits your company best. Pricing starts at 570 USD per m². Discounted rates may apply via Keeada.",
    "Booth.regular": "Regular Booth",
    "Booth.standard": "Standard",
    "Booth.booth": "9 m² Booth",
    "Booth.now": "Book Now",

    "Sponsorship.feature": "Features",
    "Sponsorship.gold": "GOLD",
    "Sponsorship.platinum": "PLATINUM",
    "Sponsorship.diamond": "DIAMOND",

    "sponsorship.llist1": "Onsite Branding",
    "sponsorship.llist2": "Match Making Lounge",
    "sponsorship.llist3": "Logo on conference website, Brochures, ICPM social media network	",
    "sponsorship.llist4": "Authorities visit to the booth",
    "sponsorship.llist5": "Company Description on Website",
    "sponsorship.llist6": "Company Recognition During",
    "sponsorship.llist7": "Exhibition Space",
    "sponsorship.llist8": "Arrange meeting with government authority",
    "sponsorship.llist9": "Arrange meeting with business partners",
    "sponsorship.llist10": "Presentation during the event",
    "sponsorship.llist11": "Free consultation by ICPM",
    "sponsorship.llist12": "Free accommodation",
    "sponsorship.llist13": "Free transportation from Hotel",
    "sponsorship.llist14": "Meeting table at conference",
    "sponsorship.llist15": "Lecture in the scientific program",

    "sponsorship.list1": "(+Signs)",
    "sponsorship.list2": "(VIP visit)",
    "sponsorship.list3": "(Highness visit)",
    "sponsorship.list4": "150 words",
    "sponsorship.list5": "200 words",
    "sponsorship.list6": "250 words",
    "sponsorship.list7": "(1st day)",
    "sponsorship.list8": "(Opening ceremony)",
    "sponsorship.list9": "Good location",
    "sponsorship.list10": "Semi Premium",
    "sponsorship.list11": "Premium position",
    "sponsorship.list12": "(Healthcare)",
    "sponsorship.list13": "(Healthcare authorities)",
    "sponsorship.list14": "1 room",
    "sponsorship.list15": "2 rooms",
    "sponsorship.list16": "3 rooms",
    "sponsorship.list17": "(VIP Table)",
    "sponsorship.list18": "(VIP Table in Event)",



    "sponsorship.gbook": "Book Now",
    "sponsorship.pbook": "Book Now",
    "sponsorship.dbook": "Book Now",

    "sponsorship.location": "See Booth Locations",
    "sponsorship.view": "View Floor Plan",




    // Final CTA Section
    "Final.title": "Ready to Join the Future of Healthcare?",
    "Final.text": "Secure your spot today and showcase your innovation at one of the most dynamic healthcare events in the Middle East.",
    "Final.apply": "Apply Now",
    "Final.book": "Book a Call",


    //Booth Application Form
    "Apply.stall":"Apply for Exhibition Booth",
    "Apply.firstName":"First Name *",
    "Apply.lastName":"Last Name *",
    "Apply.nationality":"Nationality  *",
    "Apply.selectnationality":"Select Nationality *",
    "Apply.sweden":"Sweden ",
    "Apply.denmark":"Denmark ",
    "Apply.finland":"Finland ",
    "Apply.norway":"Norway ",
    "Apply.other":"Other ",
    "Apply.emailaddress":"Email Address *",
    "Apply.fieldofcompany":"Field of Company *",
    "Apply.rbooth":"Booth *",
    "Apply.selectbooth":"Select Booth ",
    "Apply.regularbooth":"Regular Booth - $5,500",
    "Apply.gold":"GOLD - $10,260",
    "Apply.platinum":"PLATINUM - $15,390",
    "Apply.diamond":"Diamond - $20,520",
    "Apply.organizationinfo":"Organization Information",
    "Apply.organizationname":"Organization Name *",
    "Apply.organizationnumber":"Organization Number *",
    "Apply.mobile":"Mobile/Phone/Contact No. *",
    "Apply.additionalinfo":"Additional Information (Optional)",
    "Apply.close":"Close",
    "Apply.submitapplication":"Submit Application",


    // Contact Section
    "Contact.title": "Get in Touch",
    "Contact.title1": "Contact Information",
    "Contact.text": "Official Nordic Partner for ICPM 2026",
    "Contact.title3": "Email",
    "Contact.title4": "Website",
    "Contact.title5": "Download Resources",
    "Contact.icpm": "ICPM 2026 Brochure (PDF)",
    "Contact.floor": "Floor Plan (PDF)",

    "Contact.Sendtitle": "Send Us a Message",
    "Contact.Sendname": "Name",
    "Contact.Sendcompany": "Company",
    "Contact.Sendemail": "Email",
    "Contact.Sendphone": "Phone",
    "Contact.Sendtext": "I'm interested in",
    "Contact.option1": "Exhibiting at ICPM 2026",
    "Contact.option2": "Sponsorship Opportunities",
    "Contact.option3": "B2B Meetings",
    "Contact.option4": "Other",
    "Contact.message": "Message",
    "Contact.sendmessage": "Send Message",
  },
  sv: {
    // Navigation
    "nav.about": "Om ICPM",
    "nav.why": "Varför UAE?",
    "nav.benefits": "Vem Kan Delta?",
    "nav.objective": "Mål",
    "nav.future": "Framtidsplan",
    "nav.booths": "Utställningsalternativ",
    "nav.contact": "Kontakt",

    // Hero Section
    "hero.offer": "Exklusvt erbjudande",
    "hero.companies": "Skandinaviska företag får 5% rabatt genom Keeada!",
    "hero.contact": "Kontakta oss",
    "hero.claim": "för att ta del av din rabatt.",
    "hero.title": "Ta din hälsoinnovation till Mellanöstern",
    "hero.subtitle": "Ställ ut på den 14:e ICPM-konferensen 2026 i Förenade Arabemiraten",
    "hero.text": "Delta på en av Mellanösterns största utställningar inom hälso- och sjukvård samt läkemedel.<br>20-22 januari 2026 — Sharjah Research Technology & Innovation Park, Förenade Arabemiraten.",
    "hero.apply": "Ansök om utställarplats",
    "hero.download": "Ladda ner broschyr",
    "hero.call": "Boka ett möte",
    "timer.title": "TID KVAR",
    "timer.days": "DAGAR",
    "timer.hours": "TIMMAR",
    "timer.minutes": "MINUTER",
    "timer.seconds": "SEKUNDER",

    // About Section
    "about.title": "Vad är ICPM?",
    "about.text1": "ICPM är en plattform som täcker både lokala och internationella marknader. Du får den exklusiva möjligheten att träffa nyckelpersoner och beslutsfattare en-mot-en från alla GCC- och MENA-länder samt utlandet inom hälso- och sjukvårdssektorn.",
    "about.text2": "ICPM täcker områden som medicin, medicinsk turism, försäkringar, farmaceutisk utbildning, farmaceutisk industri, regulatoriska frågor, bioekvivalensstudier, farmakovigilans, medicinprissättning, tandtekniska laboratorier, tandvård, diagnostiska laboratorier, GMP-avdelningar, genetik, veterinärmedicin, estetik, dermatologi, skönhet och kosmetika, tillgänglighet och rehabilitering.",
    "about.text3": "Dessutom kommer du att möta ledande branschexperter, konsulter, vårdgivare och VD:ar inom hälso- och sjukvårdsområdet under privata sessioner och B2B-möten.",

    // Why UAE Section
    "why.title": "Varför UAE - och varför nu?",
    "why.text1": "Varje år skapar ICPM nya framgångsberättelser, och efter framgången med de 13 tidigare evenemangen i UAE samarbetar ICPM i år med myndigheter under en och samma plattform.",
    "why.text2": "UAE:s riktning och vision är att förbättra och erbjuda en världsklass hälso- och sjukvårdsindustri, utöka vårdens omfattning och vinna förtroende från både hälso- och sjukvårdsmyndigheter och vårdgivare.",
    "why.text3": "UAE:s ekonomi har upplevt en enastående tillväxt de senaste åren, vilket är resultatet av investerarvänliga policier som minskad byråkrati och utökad ekonomi och handel i UAE. Med hänsyn till dess betydelse och stödet från UAE:s ledare har ICPM tagit tillfället i akt och beslutat att organisera den 14:e upplagan av ICPM i UAE.",

    // Who Can Participate?
    "Who.title": "Vem Kan Delta?",
    "Who.text": "ICPM 2026 är idealisk för företag och organisationer inom:",
    "Who.text1": "Farmaceutiska tillverkare och bioteknikindustrier",
    "Who.text2": "Sjukhus och vårdgivare",
    "Who.text3": "Medicintekniska företag och distributörer",
    "Who.text4": "Företag inom engångsmedicinsk utrustning och förbrukningsmaterial",
    "Who.text5": "Hälso- och sjukvårdskonsulter och investerare",
    "Who.text6": "Professorer från farmaceutiska/biotekniska institut",
    "Who.text7": "Universitet och akademiker",
    "Who.text8": "Monteringsföretag (ambulanser, mobila sjukhus)",
    "Who.text9": "Hälsoförsäkringsbolag",
    "Who.text10": "Genetiska vårdcentra",
    "Who.text11": "Företag inom estetik, kosmetika och skönhet",
    "Who.text12": "Myndigheter, media och publikationer inom hälso- och sjukvård",
    "Who.text13": "Statliga kontor och kommuner",
    "Who.text14": "Veterinära fabriker, företag och distributörer",
    "Who.text15": "Läkemedelsdistributionsbyråer och vetenskapliga kontor",
    "Who.text16": "Hotell, spa, rehabiliteringsföretag och gästfrihetsbranschen",
    "Who.text17": "Ideella organisationer",
    "Who.text18": "Tillverkare av multivitaminer, organiska och växtbaserade produkter",
    "Who.text19": "Tillverkare av sport- och näringsprodukter",
    "Who.text20": "Logistik-, import- och exportföretag",
    "Who.text21": "Frizonsmyndigheter och lagerfaciliteter",

    // Purpose & Objectives of ICPM
    "Purpose.title": "Syfte & Mål med ICPM",
    "Purpose.text1": "Att främja en hälsosammare livsstil samt förebygga livsstilsrelaterade sjukdomar.",
    "Purpose.text2": "Knyta samman multinationella farmaceutiska och medicinska företag, distributörer och återförsäljare med UAE:s och GCC:s regelverkande myndigheter",
    "Purpose.text3": "Att öka medvetenheten om masssamlingsmedicin",
    "Purpose.text4": "Skapa starka kopplingar mellan universitet, tillverkare, distributörer och återförsäljare till gagn för hälso- och sjukvården",
    "Purpose.text5": "Marknadsföra, stödja och underlätta medicinsk turism i UAE",
    "Purpose.text6": "Erbjuda världsklass behandling till patienter till låg kostnad",
    "Purpose.text7": "Sammanfatta insatser mellan vetenskapliga organisationer och hälso- och sjukvårdsföretag",
    "Purpose.text8": "Dela uppdaterad information om den senaste teknologin",
    "Purpose.text9": "Främja nya affärs- och teknikidéer inom hälso- och sjukvårdssektorn",
    "Purpose.text10": "Skapa starka kopplingar mellan privata och statliga sjukhus",
    "Purpose.text11": "Öka tillgången till ett decentraliserat folkhälsoystem genom att etablera ny infrastruktur i befintliga institutioner",
    "Purpose.text12": "Utveckla inhemska farmaceutiska industrier och sjukhus",

    // Future Plan
    "Future.title": "Framtidsplan",
    "Future.text1": "Varje år kommer Keeada genom ICPM att samarbeta med olika välrenommerade hälso- och sjukvårdsföretag i UAE och runt om i världen. Eftersom detta kommer att vara länken mellan forskare och professionella, kommer alla våra ICPM-evenemang att genomföras i samarbete med de mest ansedda företagen.",
    "Future.text2": "Detta initiativ kommer att lyfta hälso- och sjukvårdsområdet och resultera i bästa möjliga utfall från vårdgivare som formar medicinens framtid.",
    "Future.title1": "Globalt Samarbete",
    "Future.text3": "Partnerskap med ledande hälso- och sjukvårdsorganisationer världen över",
    "Future.title2": "Strategiska Partnerskap",
    "Future.text4": "Bygger broar mellan forskare och branschprofessionella",
    "Future.title3": "Hållbar Tillväxt",
    "Future.text5": "Skapar långvarig påverkan inom hälso- och sjukvårdsinnovation",

    // Booth Options Section
    "Booth.title": "Båspaket och sponsringsmöjligheter",
    "Booth.text": "Välj den storlek och synlighetsnivå som passar ditt företag bäst. Priser börjar från 570 USD per m². Rabatterade priser kan gälla via Keeada.",
    "Booth.regular": "Standardboth",
    "Booth.standard": "Standard",
    "Booth.booth": "9 m² both",
    "Booth.now": "Boka nu",

    "Sponsorship.feature": "Fördelar",
    "Sponsorship.gold": "GULD",
    "Sponsorship.platinum": "PLATINA",
    "Sponsorship.diamond": "DIAMANT",

    "sponsorship.llist1": "På-plats varumärkesexponering",
    "sponsorship.llist2": "Matchmaking-lounge",
    "sponsorship.llist3": "Logo på konferenswebb, broschyrer, ICPM:s sociala medier",
    "sponsorship.llist4": "Besök från myndigheter vid er bås",
    "sponsorship.llist5": "Företagsbeskrivning på webbplats",
    "sponsorship.llist6": "Företagsuppmärksammande under eventet",
    "sponsorship.llist7": "Utställningsyta",
    "sponsorship.llist8": "Arrangera möte med myndighet",
    "sponsorship.llist9": "Arrangera möte med affärspartners",
    "sponsorship.llist10": "Presentation under eventet",
    "sponsorship.llist11": "Kostnadsfri konsultation av ICPM",
    "sponsorship.llist12": "Kostnadsfri logi",
    "sponsorship.llist13": "Kostnadsfri transport från hotell",
    "sponsorship.llist14": "Mötesbord vid konferensen",
    "sponsorship.llist15": "Föreläsning i det vetenskapliga programmet",

    "sponsorship.list1": "(+Skyltar)",
    "sponsorship.list2": "(VIP-besök)",
    "sponsorship.list3": "(Höghetsbesök)",  
    "sponsorship.list4": "150 ord",
    "sponsorship.list5": "200 ord",
    "sponsorship.list6": "250 ord",
    "sponsorship.list7": "(Första dagen)",
    "sponsorship.list8": "(Invigningsceremoni)",
    "sponsorship.list9": "Bra placering",
    "sponsorship.list10": "Semi Premium",  
    "sponsorship.list11": "Premiumplacering",
    "sponsorship.list12": "(Hälso- och sjukvård)",
    "sponsorship.list13": "(Hälso- och sjukvårdsmyndigheter)",
    "sponsorship.list14": "1 rum",  
    "sponsorship.list15": "2 rum",
    "sponsorship.list16": "3 rum",
    "sponsorship.list17": "(VIP-bord)",
    "sponsorship.list18": "(VIP-bord under eventet)",

    "sponsorship.gbook": "Boka nu",
    "sponsorship.pbook": "Boka nu",
    "sponsorship.dbook": "Boka nu",

    "sponsorship.location": "Se båsplaceringar",
    "sponsorship.view": "Visa plattskiss",

    // Final CTA Section
    "Final.title": "Redo att vara med och forma framtidens hälso- och sjukvård?",
    "Final.text": "Säkra din plats redan idag och visa upp din innovation på ett av Mellanösterns mest dynamiska hälsoevenemang.",
    "Final.apply": "Ansök nu",
    "Final.book": "Boka möte",

    //Booth Application Form
    "Apply.stall": "Ansök om utställningsyta",

    "Apply.stall": "Ansök om utställningsyta",
    "Apply.firstName": "Förnamn *",
    "Apply.lastName": "Efternamn *",
    "Apply.nationality": "Nationalitet *",
    "Apply.selectnationality": "Välj nationalitet *",
    "Apply.sweden": "Sverige",
    "Apply.denmark": "Danmark",
    "Apply.finland": "Finland",
    "Apply.norway": "Norge",
    "Apply.other": "Annan",
    "Apply.emailaddress": "E-postadress *",
    "Apply.fieldofcompany": "Företagets verksamhetsområde *",
    "Apply.rbooth": "Monter *",
    "Apply.selectbooth": "Välj monter",
    "Apply.regularbooth": "Vanlig monter – 5 500 USD",
    "Apply.gold": "GULD – 10 260 USD",
    "Apply.platinum": "PLATINA – 15 390 USD",
    "Apply.diamond": "DIAMANT – 20 520 USD",
    "Apply.organizationinfo": "Organisationsinformation",
    "Apply.organizationname": "Organisationsnamn *",
    "Apply.organizationnumber": "Organisationsnummer *",
    "Apply.mobile": "Mobil/Telefon/Kontaktnummer *",
    "Apply.additionalinfo": "Ytterligare information (valfritt)",
    "Apply.close": "Stäng",
    "Apply.submitapplication": "Skicka ansökan",


    

    // Contact Section
    "Contact.title": "Kontakta oss",
    "Contact.title1": "Kontaktinformation",
    "Contact.text": "Officiell nordisk partner för ICPM 2026",
    "Contact.title3": "E-post",
    "Contact.title4": "Webbplats",
    "Contact.title5": "Ladda ner resurser",
    "Contact.icpm": "ICPM 2026 broschyr (PDF)",
    "Contact.floor": "Planlösning (PDF)",

    "Contact.Sendtitle": "Skicka oss ett meddelande",
    "Contact.Sendname": "Namn",
    "Contact.Sendcompany": "Företag",
    "Contact.Sendemail": "E-post",
    "Contact.Sendphone": "Telefon",
    "Contact.Sendtext": "Jag är intresserad av",
    "Contact.option1": "Att ställa ut på ICPM 2026",
    "Contact.option2": "Sponsringsmöjligheter",
    "Contact.option3": "B2B-möten",
    "Contact.option4": "Annat",
    "Contact.message": "Meddelande",
    "Contact.sendmessage": "Skicka meddelande"
  },
  no: { 
    // Navigation
    "nav.about": "Om ICPM",
    "nav.why": "Hvorfor UAE?",
    "nav.benefits": "Hvem Kan Delta?",
    "nav.objective": "Mål",
    "nav.future": "Fremtidsplan",
    "nav.booths": "Standalternativer",
    "nav.contact": "Kontakt",

    // Hero Section
    "hero.offer": "Eksklusivt tilbud",
    "hero.companies": "Skandinaviske selskaper får 5% rabatt gjennom Keeada!",
    "hero.contact": "Kontakt oss",
    "hero.claim": "for å hente din rabatt.",
    "hero.title": "Ta din helseinnovasjon til Midtøsten",
    "hero.subtitle": "Still ut på den 14. ICPM-konferansen 2026 i UAE",
    "hero.text": "Bli med på en av Midtøstens største helse- og farmasimesser.<br>20.-22. januar 2026 — Sharjah Research Technology & Innovation Park, UAE.",
    "hero.apply": "Søk som utstiller",
    "hero.download": "Last ned brosjyre",
    "hero.call": "Bestill samtale",
    "timer.title": "TID IGJEN",
    "timer.days": "DAGER",
    "timer.hours": "TIMER",
    "timer.minutes": "MINUTTER",
    "timer.seconds": "SEKUNDER",

    // About Section
    "about.title": "Hva er ICPM?",
    "about.text1": "ICPM er en plattform som dekker både lokale og internasjonale markeder, hvor du får en eksklusiv mulighet til å møte nøkkelmyndigheter og beslutningstakere fra alle GCC- og MENA-land samt utlandet i helsesektoren.",
    "about.text2": "ICPM dekker medisin, medisinsk turisme, forsikring, farmasøytisk utdanning, farmasøytisk industri, regulatoriske saker, bioekvivalensstudier, farmakovigilans, legemiddelpriser, tannlaboratorier, tannhelse, diagnostiske laboratorier, GMP-avdeling, genetikk, veterinærmedisin, estetikk, dermatologi, skjønnhet og kosmetikk, tilgjengelighet og rehabilitering.",
    "about.text3": "I tillegg vil du møte ledende bransjeeksperter, konsulenter, helsepersonell og administrerende direktører i helsesektoren i private økter og B2B-møter.",

    // Why UAE Section
    "why.title": "Hvorfor UAE — og hvorfor nå?",
    "why.text1": "Hvert år inngår ICPM nye suksesshistorier, og etter suksessen med de 13 foregående arrangementene i UAE, samarbeider ICPM i år med myndigheter under én plattform.",
    "why.text2": "UAEs retning og visjon er å forbedre og tilby en verdensklasse helseindustri, utvide helseomsorgens omfang og vinne tillit fra både helsemyndigheter og helsepersonell.",
    "why.text3": "UAEs økonomi har hatt en enestående vekst de siste årene som følge av investorvennlige politikk som redusert byråkrati og utvidet økonomi og handel i UAE. Med tanke på betydningen og støtten fra UAEs ledere, har ICPM bestemt seg for å gripe muligheten og arrangere den 14. utgaven av ICPM i UAE.",

    // Who Can Participate?
    "Who.title": "Hvem kan delta?",
    "Who.text": "ICPM 2026 er ideell for selskaper og organisasjoner innen:",
    "Who.text1": "Farmasøytiske produsenter og bioteknologibedrifter",
    "Who.text2": "Sykehus og helsetilbydere",
    "Who.text3": "Medisinsk utstyrselskaper og distributører",
    "Who.text4": "Selskaper for engangsmedisinsk utstyr og forbruksmateriell",
    "Who.text5": "Helsekonsulenter og investorer",
    "Who.text6": "Professorer fra farmasøytiske/bioteknologiske institutter",
    "Who.text7": "Universiteter og akademikere",
    "Who.text8": "Monteringsselskaper (ambulanse, mobile sykehus)",
    "Who.text9": "Helseforsikringsselskaper",
    "Who.text10": "Helsegenetiske sentre",
    "Who.text11": "Estetikk-, kosmetikk- og skjønnhetsselskaper",
    "Who.text12": "Helsemyndigheter, media og publikasjoner",
    "Who.text13": "Statlige kontorer og kommuner",
    "Who.text14": "Veterinærfabrikker, selskaper og distributører",
    "Who.text15": "Legemiddeldistribusjonsbyråer og vitenskapelige kontorer",
    "Who.text16": "Overnattingssteder, hoteller, spa, rehabiliteringsselskaper",
    "Who.text17": "Idealorganisasjoner",
    "Who.text18": "Produsenter av multivitaminer, organiske og urtebaserte produkter",
    "Who.text19": "Produsenter av sports- og ernæringsprodukter",
    "Who.text20": "Logistikk-, import- og eksportselskaper",
    "Who.text21": "Frisonsmyndigheter og lagerfasiliteter",

    // Purpose & Objectives of ICPM
    "Purpose.title": "Formål og mål med ICPM",
    "Purpose.text1": "Å fremme en sunnere livsstil samt forebygge livsstilsrelaterte sykdommer.",
    "Purpose.text2": "Knytte sammen multinasjonale farmasøytiske og medisinske selskaper, distributører og detaljister med UAEs og GCCs regulatoriske myndigheter",
    "Purpose.text3": "Å øke bevisstheten om medisin for massesamlinger",
    "Purpose.text4": "Skape sterke forbindelser mellom universiteter, produsenter, distributører og detaljister til gagn for helsevesenet",
    "Purpose.text5": "Fremme, støtte og tilrettelegge for medisinsk turisme i UAE",
    "Purpose.text6": "Tilby verdensklasse behandling til pasienter til lav kostnad",
    "Purpose.text7": "Samle innsatser mellom vitenskapelige organisasjoner og helseselskaper",
    "Purpose.text8": "Dele oppdatert informasjon om den nyeste teknologien",
    "Purpose.text9": "Fremme nye forretnings- og teknologideer i helsesektoren",
    "Purpose.text10": "Skape sterke forbindelser mellom private og statlige sykehus",
    "Purpose.text11": "Å øke tilgangen til et desentralisert folkehelsesystem ved å etablere ny infrastruktur i eksisterende institusjoner",
    "Purpose.text12": "Utvikle innenlandsk farmasøytisk industri og sykehus",

    // Future Plan
    "Future.title": "Fremtidsplan",
    "Future.text1": "Hvert år vil Keeada gjennom ICPM samarbeide med ulike anerkjente helseselskaper i UAE og over hele verden. Ettersom dette vil være bindeleddet mellom forskere og fagfolk, vil alle våre ICPM-arrangementer bli avholdt i samarbeid med de mest anerkjente selskapene.",
    "Future.text2": "Dette initiativet vil løfte helsesektoren og resultere i de beste resultatene fra helsetilbydere som former fremtidens medisin.",
    "Future.title1": "Globalt samarbeid",
    "Future.text3": "Partnerskap med ledende helseorganisasjoner verden over",
    "Future.title2": "Strategiske partnerskap",
    "Future.text4": "Bygger broer mellom forskere og bransjeprofesjonelle",
    "Future.title3": "Bærekraftig vekst",
    "Future.text5": "Skapper varig innvirkning på helseinnovasjon",

    // Booth Options Section
    "Booth.title": "Standpakker og sponsormuligheter",
    "Booth.text": "Velg den størrelsen og synlighetsgraden som passer best for ditt selskap. Priser starter fra 570 USD per m². Reduserte priser kan gjelde via Keeada.",
    "Booth.regular": "Standardstand",
    "Booth.standard": "Standard",
    "Booth.booth": "9 m² stand",
    "Booth.now": "Bestill nå",

    "Sponsorship.feature": "Funksjoner",
    "Sponsorship.gold": "GULL",
    "Sponsorship.platinum": "PLATINA",
    "Sponsorship.diamond": "DIAMANT",

    "sponsorship.llist1": "Påstedet merkevarebygging",
    "sponsorship.llist2": "Matchmaking-lounge",
    "sponsorship.llist3": "Logo på konferansens nettsted, brosjyrer, ICPMs sosiale medier",
    "sponsorship.llist4": "Besøk fra myndigheter til standen",
    "sponsorship.llist5": "Selskapsbeskrivelse på nettstedet",
    "sponsorship.llist6": "Selskapsgjenkjennelse under",
    "sponsorship.llist7": "Utstillingsplass",
    "sponsorship.llist8": "Arrangere møte med myndighet",
    "sponsorship.llist9": "Arrangere møte med forretningspartnere",
    "sponsorship.llist10": "Presentasjon under arrangementet",
    "sponsorship.llist11": "Gratis konsultasjon fra ICPM",
    "sponsorship.llist12": "Gratis overnatting",
    "sponsorship.llist13": "Gratis transport fra hotell",
    "sponsorship.llist14": "Møtebord på konferansen",
    "sponsorship.llist15": "Forelesning i det vitenskapelige programmet",

    "sponsorship.list1": "(+Skilt)",
    "sponsorship.list2": "(VIP-besøk)",
    "sponsorship.list3": "(Høyhetsbesøk)",
    "sponsorship.list4": "150 ord",
    "sponsorship.list5": "200 ord",
    "sponsorship.list6": "250 ord",
    "sponsorship.list7": "(1. dag)",
    "sponsorship.list8": "(Åpningsseremoni)",
    "sponsorship.list9": "God beliggenhet",
    "sponsorship.list10": "Semi Premium",
    "sponsorship.list11": "Premiumplassering",
    "sponsorship.list12": "(Helsevesen)",
    "sponsorship.list13": "(Helsemyndigheter)",
    "sponsorship.list14": "1 rom",
    "sponsorship.list15": "2 rom",
    "sponsorship.list16": "3 rom",
    "sponsorship.list17": "(VIP-bord)",
    "sponsorship.list18": "(VIP-bord under arrangementet)",

    "sponsorship.gbook": "Bestill nå",
    "sponsorship.pbook": "Bestill nå",
    "sponsorship.dbook": "Bestill nå",

    "sponsorship.location": "Se standplasseringer",
    "sponsorship.view": "Se plantegning",

    // Final CTA Section
    "Final.title": "Klar for å bli med i fremtidens helsevesen?",
    "Final.text": "Sikre din plass i dag og vis frem din innovasjon på en av Midtøstens mest dynamiske helsearrangementer.",
    "Final.apply": "Søk nå",
    "Final.book": "Bestill samtale",

    //Booth Application Form
    "Apply.stall":"Søk om utstillingsstand",
    "Apply.firstName":"Fornavn *",
    "Apply.lastName":"Etternavn *",
    "Apply.nationality":"Nasjonalitet *",
    "Apply.selectnationality":"Velg nasjonalitet *",
    "Apply.sweden":"Sverige",
    "Apply.denmark":"Danmark",
    "Apply.finland":"Finland",
    "Apply.norway":"Norge",
    "Apply.other":"Annet",
    "Apply.emailaddress":"E-postadresse *",
    "Apply.fieldofcompany":"Selskapsfelt *",
    "Apply.rbooth":"Stand *",
    "Apply.selectbooth":"Velg stand",
    "Apply.regularbooth":"Standardstand - $5,500",
    "Apply.gold":"GULL - $10,260",
    "Apply.platinum":"PLATINA - $15,390",
    "Apply.diamond":"DIAMANT - $20,520",
    "Apply.organizationinfo":"Organisasjonsinformasjon",
    "Apply.organizationname":"Organisasjonsnavn *",
    "Apply.organizationnumber":"Organisasjonsnummer *",
    "Apply.mobile":"Mobil/Telefon/Kontaktnummer *",
    "Apply.additionalinfo":"Tilleggsinformasjon (Valgfri)",
    "Apply.close":"Lukk",
    "Apply.submitapplication":"Send søknad",

    // Contact Section
    "Contact.title": "Ta kontakt",
    "Contact.title1": "Kontaktinformasjon",
    "Contact.text": "Offisiell nordisk partner for ICPM 2026",
    "Contact.title3": "E-post",
    "Contact.title4": "Nettsted",
    "Contact.title5": "Last ned ressurser",
    "Contact.icpm": "ICPM 2026-brosjyre (PDF)",
    "Contact.floor": "Plantegning (PDF)",

    "Contact.Sendtitle": "Send oss en melding",
    "Contact.Sendname": "Navn",
    "Contact.Sendcompany": "Selskap",
    "Contact.Sendemail": "E-post",
    "Contact.Sendphone": "Telefon",
    "Contact.Sendtext": "Jeg er interessert i",
    "Contact.option1": "Å stille ut på ICPM 2026",
    "Contact.option2": "Sponsormuligheter",
    "Contact.option3": "B2B-møter",
    "Contact.option4": "Annet",
    "Contact.message": "Melding",
    "Contact.sendmessage": "Send melding"

  },
  dk: { 
    // Navigation
    "nav.about": "Om ICPM",
    "nav.why": "Hvorfor UAE?",
    "nav.benefits": "Hvem kan deltage?",
    "nav.objective": "Mål",
    "nav.future": "Fremtidsplan",
    "nav.booths": "Standmuligheder",
    "nav.contact": "Kontakt",

    // Hero Section
    "hero.offer": "Eksklusivt tilbud",
    "hero.companies": "Skandinaviske virksomheder får 5% rabat gennem Keeada!",
    "hero.contact": "Kontakt os",
    "hero.claim": "for at få din rabat.",
    "hero.title": "Tag din sundhedsinnovation til Mellemøsten",
    "hero.subtitle": "Udstil ved den 14. ICPM-konference 2026 i UAE",
    "hero.text": "Deltag i en af Mellemøstens største sundheds- og farmaceutiske messer.<br>20.-22. januar 2026 — Sharjah Research Technology & Innovation Park, UAE.",
    "hero.apply": "Ansøg som udstiller",
    "hero.download": "Download brochure",
    "hero.call": "Planlæg et opkald",
    "timer.title": "TID TILBAGE",
    "timer.days": "DAGE",
    "timer.hours": "TIMER",
    "timer.minutes": "MINUTTER",
    "timer.seconds": "SEKUNDER",

    // About Section
    "about.title": "Hvad er ICPM?",
    "about.text1": "ICPM er en platform, der dækker både lokale og internationale markeder, hvor du får en eksklusiv mulighed for at møde nøglemyndigheder og beslutningstagere fra alle GCC- og MENA-lande samt oversøiske markeder inden for sundhedssektoren.",
    "about.text2": "ICPM dækker medicin, medicinsk turisme, forsikring, farmaceutisk uddannelse, farmaceutisk industri, regulatoriske anliggender, bioækvivalensundersøgelser, farmakovigilans, medicinpriser, tandlaboratorier, tandpleje, diagnostiske laboratorier, GMP-afdeling, genetik, veterinærmedicin, æstetik, dermatologi, skønhed og kosmetik, tilgængelighed og rehabilitering.",
    "about.text3": "Desuden vil du møde førende brancheeksperter, konsulenter, sundhedsudbydere og direktører inden for sundhedssektoren i private sessioner og B2B-møder.",

    // Why UAE Section
    "why.title": "Hvorfor UAE — og hvorfor nu?",
    "why.text1": "Hvert år indgår ICPM nye succeshistorier, og efter succesen med de sidste 13 begivenheder i UAE, samarbejder ICPM i år med myndigheder under én platform.",
    "why.text2": "UAEs retning og vision er at forbedre og tilbyde en verdensklasse sundhedsindustri, udvide sundhedsområdet og vinde tillid fra både sundhedsmyndigheder og sundhedsudbydere.",
    "why.text3": "UAEs økonomi har oplevet en enestående vækst over de seneste år, som er resultatet af investervenlige politikker som reduktion af bureaukrati og udvidelse af økonomi og handel i UAE. I betragtning af dens betydning og den støtte, der ydes af UAEs herskere, besluttede ICPM at benytte lejligheden og organisere den 14. udgave af ICPM i UAE.",

    // Who Can Participate?
    "Who.title": "Hvem kan deltage?",
    "Who.text": "ICPM 2026 er ideel for virksomheder og organisationer inden for:",
    "Who.text1": "Farmaceutiske producenter og bioteknologivirksomheder",
    "Who.text2": "Hospitaler og sundhedsudbydere",
    "Who.text3": "Medicinsk udstyr virksomheder og distributører",
    "Who.text4": "Virksomheder for engangsmedicinsk udstyr og forbrugsmaterialer",
    "Who.text5": "Sundhedskonsulenter og investorer",
    "Who.text6": "Professorer fra farmaceutiske/bioteknologiske institutter",
    "Who.text7": "Universiteter og akademikere",
    "Who.text8": "Samlevirksomheder (ambulance, mobile hospitaler)",
    "Who.text9": "Sundhedsforsikringsselskaber",
    "Who.text10": "Sundhedsgenetiske centre",
    "Who.text11": "Æstetik-, kosmetik- og skønhedsvirksomheder",
    "Who.text12": "Sundhedsmyndigheder, medier og publikationer",
    "Who.text13": "Statskontorer og kommuner",
    "Who.text14": "Veterinærfabrikker, virksomheder og distributører",
    "Who.text15": "Lægemiddeldistributionsbureauer og videnskabelige kontorer",
    "Who.text16": "Gæstfrihed, hoteller, spa, rehabiliteringsvirksomheder",
    "Who.text17": "Non-profit organisationer",
    "Who.text18": "Producenter af multivitaminer, organiske og urtebaserede produkter",
    "Who.text19": "Producenter af sports- og ernæringsprodukter",
    "Who.text20": "Logistik-, import- og eksportvirksomheder",
    "Who.text21": "Frizonemyndigheder og lagerfaciliteter",

    // Purpose & Objectives of ICPM
    "Purpose.title": "Formål og mål med ICPM",
    "Purpose.text1": "At fremme en sundere livsstil samt forebygge livsstilsrelaterede sygdomme.",
    "Purpose.text2": "Forbinde multinationale farmaceutiske og medicinske virksomheder, distributører og detailhandlere med UAEs og GCC's regulatoriske myndigheder",
    "Purpose.text3": "At fremhæve bevidstheden om medicin til massesamlinger",
    "Purpose.text4": "Skabe stærke forbindelser mellem universiteter, producenter, distributører og detailhandlere til gavn for sundhedssektoren",
    "Purpose.text5": "Fremme, støtte og lette den medicinske turisme i UAE",
    "Purpose.text6": "Tilby verdensklasse behandling til patienter til lav pris",
    "Purpose.text7": "Konsolidere indsatser mellem videnskabelige organisationer og sundhedsvirksomheder",
    "Purpose.text8": "Dele opdateret information om den nyeste teknologi",
    "Purpose.text9": "Fremme nye forretnings- og teknologitanker inden for sundhedssektoren",
    "Purpose.text10": "Skabe stærke forbindelser mellem private og statslige hospitaler",
    "Purpose.text11": "At øge adgangen til det decentraliserede offentlige sundhedssystem ved at etablere ny infrastruktur i eksisterende institutioner",
    "Purpose.text12": "Udvikling af indenlandske farmaceutiske industrier og hospitaler",

    // Future Plan
    "Future.title": "Fremtidsplan",
    "Future.text1": "Hvert år vil Keeada gennem ICPM samarbejde med forskellige anerkendte sundhedsvirksomheder i UAE og over hele verden. Da dette vil være forbindelsen mellem forskere og fagfolk, vil alle vores ICPM-begivenheder blive afholdt i samarbejde med de mest anerkendte virksomheder.",
    "Future.text2": "Denne initiativ vil løfte sundhedssektoren og resultere i de bedste resultater fra sundhedsudbydere, der former fremtidens medicin.",
    "Future.title1": "Globalt samarbejde",
    "Future.text3": "Partnerskab med førende sundhedsorganisationer verden over",
    "Future.title2": "Strategiske partnerskaber",
    "Future.text4": "Bygge broer mellem forskere og branchefagfolk",
    "Future.title3": "Bæredygtig vækst",
    "Future.text5": "Skabe varig indflydelse på sundhedsinnovation",

    // Booth Options Section
    "Booth.title": "Standpakker og sponsormuligheder",
    "Booth.text": "Vælg den størrelse og synlighedsniveau, der passer bedst til din virksomhed. Priser starter fra 570 USD per m². Der kan gælde nedsatte priser via Keeada.",
    "Booth.regular": "Standardstand",
    "Booth.standard": "Standard",
    "Booth.booth": "9 m² stand",
    "Booth.now": "Book nu",

    "Sponsorship.feature": "Funktioner",
    "Sponsorship.gold": "GULD",
    "Sponsorship.platinum": "PLATIN",
    "Sponsorship.diamond": "DIAMANT",

    "sponsorship.llist1": "Branding på stedet",
    "sponsorship.llist2": "Matchmaking lounge",
    "sponsorship.llist3": "Logo på konferencens hjemmeside, brochurer, ICPM's sociale medier",
    "sponsorship.llist4": "Besøg fra myndigheder til standen",
    "sponsorship.llist5": "Virksomhedsbeskrivelse på hjemmesiden",
    "sponsorship.llist6": "Virksomhedsanerkendelse under",
    "sponsorship.llist7": "Udstillingsplads",
    "sponsorship.llist8": "Arrangere møde med myndighed",
    "sponsorship.llist9": "Arrangere møde med forretningspartnere",
    "sponsorship.llist10": "Præsentation under begivenheden",
    "sponsorship.llist11": "Gratis konsultation fra ICPM",
    "sponsorship.llist12": "Gratis logi",
    "sponsorship.llist13": "Gratis transport fra hotel",
    "sponsorship.llist14": "Mødebord ved konferencen",
    "sponsorship.llist15": "Foredrag i det videnskabelige program",

    "sponsorship.list1": "(+Skilte)",
    "sponsorship.list2": "(VIP-besøg)",
    "sponsorship.list3": "(Højhedsbesøg)",
    "sponsorship.list4": "150 ord",
    "sponsorship.list5": "200 ord",
    "sponsorship.list6": "250 ord",
    "sponsorship.list7": "(1. dag)",
    "sponsorship.list8": "(Åbningsceremoni)",
    "sponsorship.list9": "God placering",
    "sponsorship.list10": "Semi Premium",
    "sponsorship.list11": "Premium placering",
    "sponsorship.list12": "(Sundhedssektoren)",
    "sponsorship.list13": "(Sundhedsmyndigheder)",
    "sponsorship.list14": "1 værelse",
    "sponsorship.list15": "2 værelser",
    "sponsorship.list16": "3 værelser",
    "sponsorship.list17": "(VIP-bord)",
    "sponsorship.list18": "(VIP-bord under begivenheden)",

    "sponsorship.gbook": "Book nu",
    "sponsorship.pbook": "Book nu",
    "sponsorship.dbook": "Book nu",

    "sponsorship.location": "Se standplaceringer",
    "sponsorship.view": "Se plantegning",

    // Final CTA Section
    "Final.title": "Klar til at deltage i sundhedssektorens fremtid?",
    "Final.text": "Sikre din plads i dag og vis din innovation frem ved en af Mellemøstens mest dynamiske sundhedsbegivenheder.",
    "Final.apply": "Ansøg nu",
    "Final.book": "Book et opkald",

    //Booth Application Form
    "Apply.stall":"Ansøg om udstillingsstand",
    "Apply.firstName":"Fornavn *",
    "Apply.lastName":"Efternavn *",
    "Apply.nationality":"Nationalitet *",
    "Apply.selectnationality":"Vælg nationalitet *",
    "Apply.sweden":"Sverige",
    "Apply.denmark":"Danmark",
    "Apply.finland":"Finland",
    "Apply.norway":"Norge",
    "Apply.other":"Andet",
    "Apply.emailaddress":"E-mailadresse *",
    "Apply.fieldofcompany":"Virksomhedsområde *",
    "Apply.rbooth":"Stand *",
    "Apply.selectbooth":"Vælg stand",
    "Apply.regularbooth":"Standardstand - $5,500",
    "Apply.gold":"GULD - $10,260",
    "Apply.platinum":"PLATIN - $15,390",
    "Apply.diamond":"DIAMANT - $20,520",
    "Apply.organizationinfo":"Organisationsinformation",
    "Apply.organizationname":"Organisationsnavn *",
    "Apply.organizationnumber":"Organisationsnummer *",
    "Apply.mobile":"Mobil/Telefon/Kontaktnummer *",
    "Apply.additionalinfo":"Yderligere information (Valgfrit)",
    "Apply.close":"Luk",
    "Apply.submitapplication":"Indsend ansøgning",

    // Contact Section
    "Contact.title": "Kom i kontakt",
    "Contact.title1": "Kontaktinformation",
    "Contact.text": "Officiel nordisk partner for ICPM 2026",
    "Contact.title3": "E-mail",
    "Contact.title4": "Hjemmeside",
    "Contact.title5": "Download ressourcer",
    "Contact.icpm": "ICPM 2026 brochure (PDF)",
    "Contact.floor": "Plantegning (PDF)",

    "Contact.Sendtitle": "Send os en besked",
    "Contact.Sendname": "Navn",
    "Contact.Sendcompany": "Virksomhed",
    "Contact.Sendemail": "E-mail",
    "Contact.Sendphone": "Telefon",
    "Contact.Sendtext": "Jeg er interesseret i",
    "Contact.option1": "At udstille ved ICPM 2026",
    "Contact.option2": "Sponsormuligheder",
    "Contact.option3": "B2B-møder",
    "Contact.option4": "Andet",
    "Contact.message": "Besked",
    "Contact.sendmessage": "Send besked"
    
  },
  fi: { 
    // Navigation
    "nav.about": "Tietoa ICPM:stä",
    "nav.why": "Miksi UAE?",
    "nav.benefits": "Kuka voi osallistua?",
    "nav.objective": "Tavoitteet",
    "nav.future": "Tulevaisuus",
    "nav.booths": "Standivaihtoehdot",
    "nav.contact": "Yhteystiedot",

    // Hero Section
    "hero.offer": "Eksklusiivinen tarjous",
    "hero.companies": "Skandinaaviset yritykset saavat 5% alennuksen Keeadan kautta!",
    "hero.contact": "Ota yhteyttä",
    "hero.claim": "ja nosta alennuksesi.",
    "hero.title": "Vie terveydenhuollon innovaatiosi Lähi-itään",
    "hero.subtitle": "Osallistu 14. ICPM-konferenssiin 2026 UAE:ssa",
    "hero.text": "Liity mukaan yhteen Lähi-idän suurimmista terveys- ja lääketeollisuuden näyttelyistä.<br>20.-22. tammikuuta 2026 — Sharjah Research Technology & Innovation Park, UAE.",
    "hero.apply": "Hae näyttelytilaa",
    "hero.download": "Lataa esite",
    "hero.call": "Varaa puhelinaika",
    "timer.title": "AIKAA JÄLJELLÄ",
    "timer.days": "PÄIVÄÄ",
    "timer.hours": "TUNTIA",
    "timer.minutes": "MINUUTTIA",
    "timer.seconds": "SEKUNTIA",

    // About Section
    "about.title": "Mikä on ICPM?",
    "about.text1": "ICPM on alusta, joka kattaa paikalliset ja kansainväliset markkinat, ja sinulla on ainutlaatuinen mahdollisuus tavata kasvokkain keskeiset viranomaiset ja päätöksentekijät kaikista GCC- ja MENA-maista sekä ulkomailta terveydenhuollon alalta.",
    "about.text2": "ICPM kattaa lääketieteen, lääketurismin, vakuutukset, farmasian koulutuksen, lääketeollisuuden, sääntelyasiat, bioekvivalenssitutkimukset, farmakovigilanssin, lääkkeiden hinnoittelun, hammaslaboratoriot, hammashoidon, diagnostiset laboratoriot ja GMP-osaston, genetiikan, eläinlääketieteen, estetiikan, ihotautien, kauneuden ja kosmetiikan, saavutettavuuden ja kuntoutuksen.",
    "about.text3": "Lisäksi kohtaat alan johtavia asiantuntijoita, konsultteja, terveydenhuollon tarjoajia ja toimitusjohtajia terveydenhuollon alalta yksityisissä istunnoissa ja B2B-tapaamisissa.",

    // Why UAE Section
    "why.title": "Miksi UAE — ja miksi nyt?",
    "why.text1": "Joka vuosi ICPM solmii uusia menestystarinoita, ja viimeisten 13 tapahtuman menestyksen jälkeen UAE:ssa ICPM tekee tänä vuonna yhteistyötä hallituksen viranomaisten kanssa yhden alustan alla.",
    "why.text2": "UAE:n suunta ja visio on parantaa ja tarjota maailmanluokan terveydenhuoltoala, laajentaa terveydenhoidon soveltamisalaa ja ansaita terveydenhuollon viranomaisten ja terveydenhuollon tarjoajien luottamus.",
    "why.text3": "UAE:n talous on kokenut ennennäkemättömän kasvun viime vuosina, mikä on seurausta sijoittajaystävällisistä politiikoista, kuten byrokratian vähentämisestä ja talouden ja kaupankäynnin laajentamisesta UAE:ssa. Ottaen huomioon sen merkityksen ja UAE:n hallitsijoiden antaman tuen, ICPM päätti tarttua tilaisuuteen ja järjestää ICPM:n 14. painoksen UAE:ssa.",

    // Who Can Participate?
    "Who.title": "Kuka voi osallistua?",
    "Who.text": "ICPM 2026 on ihanteellinen seuraaville yrityksille ja organisaatioille:",
    "Who.text1": "Lääkkeiden valmistajat ja biotekniikka-alan yritykset",
    "Who.text2": "Sairaalat ja terveydenhuollon tarjoajat",
    "Who.text3": "Lääkintävälineyritykset ja jakelijat",
    "Who.text4": "Kertakäyttölääkintätarvikkeet ja kulutustarvikkeet valmistavat yritykset",
    "Who.text5": "Terveydenhuollon konsultit ja sijoittajat",
    "Who.text6": "Professorit farmasian/biotekniikan instituuteista",
    "Who.text7": "Yliopistot ja akateemikot",
    "Who.text8": "Kokoonpanoyritykset (ambulanssit, matkailusairaalat)",
    "Who.text9": "Terveysvakuutusyhtiöt",
    "Who.text10": "Terveydenhuollon genetiikkakeskukset",
    "Who.text11": "Estetiikka-, kosmetiikka- ja kauneusalan yritykset",
    "Who.text12": "Terveydenhuollon viranomaiset, media ja julkaisut",
    "Who.text13": "Hallituksen toimistot ja kunnat",
    "Who.text14": "Eläinlääketieteen tehtaat, yritykset ja jakelijat",
    "Who.text15": "Lääkejakeluyritykset ja tieteelliset toimistot",
    "Who.text16": "Majoitus-, hotelli-, kylpylä- ja kuntoutusyritykset",
    "Who.text17": "Voittoa tavoittelemattomat järjestöt",
    "Who.text18": "Multivitamiinien, luonnon- ja kasviperäisten tuotteiden valmistajat",
    "Who.text19": "Urheilu- ja ravintotuotteiden valmistajat",
    "Who.text20": "Logistiikka-, tuonti- ja vientiyritykset",
    "Who.text21": "Vapaavyöhykkeiden viranomaiset ja varastotilat",

    // Purpose & Objectives of ICPM
    "Purpose.title": "ICPM:n tarkoitus ja tavoitteet",
    "Purpose.text1": "Edistää terveellisempää elämäntapaa sekä ehkäistä elämäntapaan liittyviä sairauksia.",
    "Purpose.text2": "Yhdistää monikansalliset lääke- ja lääketeollisuusyritykset, jakelijat ja vähittäiskauppiaat UAE:n ja GCC:n sääntelyviranomaisiin",
    "Purpose.text3": "Korostaa tietoisuutta joukkokokoontumislääketieteestä",
    "Purpose.text4": "Luoda vahva yhteys yliopistojen, valmistajien, jakelijoiden ja vähittäiskauppiaiden välille terveydenhoidon hyväksi",
    "Purpose.text5": "Edistää, tukea ja helpottaa lääketurismia UAE:ssa",
    "Purpose.text6": "Tarjota maailmanluokan hoitoa potilaille edullisesti",
    "Purpose.text7": "Yhdistää tieteellisten organisaatioiden ja terveydenhuollon yritysten ponnisteluja",
    "Purpose.text8": "Jakaa päivitettyä tietoa uusimmista teknologioista",
    "Purpose.text9": "Edistää uusia liike- ja teknologiaideoita terveydenhuollon alalla",
    "Purpose.text10": "Luoda vahva yhteys yksityisten ja julkisten sairaaloiden välille",
    "Purpose.text11": "Lisätä pääsyä hajautettuun kansanterveysjärjestelmään luomalla uutta infrastruktuuria olemassa oleviin laitoksiin",
    "Purpose.text12": "Kehittää kotimaista lääketeollisuutta ja sairaaloita",

    // Future Plan
    "Future.title": "Tulevaisuuden suunnitelma",
    "Future.text1": "Joka vuosi Keeada ICPM:n kautta tekee yhteistyötä erilaisten arvostettujen terveydenhuollon yritysten kanssa UAE:ssa ja ympäri maailmaa. Koska tästä tulee linkki tutkijoiden ja ammattilaisten välille, kaikki ICPM-tapahtumamme järjestetään yhteistyössä arvostetuimpien yritysten kanssa.",
    "Future.text2": "Tämä aloite nostaa terveydenhuollon alaa ja johtaa parhaisiin tuloksiin terveydenhuollon tarjoajilta, jotka muokkaavat lääketieteen tulevaisuutta.",
    "Future.title1": "Maailmanlaajuinen yhteistyö",
    "Future.text3": "Yhteistyö johtavien terveydenhuollon organisaatioiden kanssa maailmanlaajuisesti",
    "Future.title2": "Strategiset kumppanuudet",
    "Future.text4": "Siltojen rakentaminen tutkijoiden ja alan ammattilaisten välille",
    "Future.title3": "Kestävää kasvua",
    "Future.text5": "Kestävän vaikutuksen luominen terveydenhuollon innovaatioihin",

    // Booth Options Section
    "Booth.title": "Standipaketit ja sponsoroimismahdollisuudet",
    "Booth.text": "Valitse yrityksellesi sopivin koko ja näkyvyystaso. Hinnat alkavat 570 USD/m². Keeadan kautta voi saada alennuksia.",
    "Booth.regular": "Tavallinen standi",
    "Booth.standard": "Standardi",
    "Booth.booth": "9 m² standi",
    "Booth.now": "Varaa nyt",

    "Sponsorship.feature": "Ominaisuudet",
    "Sponsorship.gold": "KULTA",
    "Sponsorship.platinum": "PLATINA",
    "Sponsorship.diamond": "TIMANTTI",

    "sponsorship.llist1": "Paikan päällä tapahtuva brändäys",
    "sponsorship.llist2": "Matchmaking lounge",
    "sponsorship.llist3": "Logo konferenssin verkkosivustolla, esitteissä, ICPM:n sosiaalisessa mediassa",
    "sponsorship.llist4": "Viranomaisten vierailu standilla",
    "sponsorship.llist5": "Yrityksen kuvaus verkkosivustolla",
    "sponsorship.llist6": "Yrityksen tunnustaminen tapahtuman aikana",
    "sponsorship.llist7": "Näyttelytila",
    "sponsorship.llist8": "Tapaamisen järjestäminen hallituksen viranomaisen kanssa",
    "sponsorship.llist9": "Tapaamisen järjestäminen liikekumppaneiden kanssa",
    "sponsorship.llist10": "Esitys tapahtuman aikana",
    "sponsorship.llist11": "Ilmainen konsultaatio ICPM:ltä",
    "sponsorship.llist12": "Ilmainen majoitus",
    "sponsorship.llist13": "Ilmainen kuljetus hotellista",
    "sponsorship.llist14": "Kokouspöytä konferenssissa",
    "sponsorship.llist15": "Luento tieteellisessä ohjelmassa",

    "sponsorship.list1": "(+Kyltit)",
    "sponsorship.list2": "(VIP-vierailu)",
    "sponsorship.list3": "(Korkeuden vierailu)",
    "sponsorship.list4": "150 sanaa",
    "sponsorship.list5": "200 sanaa",
    "sponsorship.list6": "250 sanaa",
    "sponsorship.list7": "(1. päivä)",
    "sponsorship.list8": "(Avajaiset)",
    "sponsorship.list9": "Hyvä sijainti",
    "sponsorship.list10": "Semi Premium",
    "sponsorship.list11": "Premium-sijainti",
    "sponsorship.list12": "(Terveydenhuolto)",
    "sponsorship.list13": "(Terveydenhuollon viranomaiset)",
    "sponsorship.list14": "1 huone",
    "sponsorship.list15": "2 huonetta",
    "sponsorship.list16": "3 huonetta",
    "sponsorship.list17": "(VIP-pöytä)",
    "sponsorship.list18": "(VIP-pöytä tapahtumassa)",

    "sponsorship.gbook": "Varaa nyt",
    "sponsorship.pbook": "Varaa nyt",
    "sponsorship.dbook": "Varaa nyt",

    "sponsorship.location": "Katso standien sijainnit",
    "sponsorship.view": "Katso pohjapiirros",

    // Final CTA Section
    "Final.title": "Valmiina liittymään terveydenhuollon tulevaisuuteen?",
    "Final.text": "Varmista paikkasi jo tänään ja esittele innovaatiotasi yhdellä Lähi-idän dynaamisimmista terveystapahtumista.",
    "Final.apply": "Hae nyt",
    "Final.book": "Varaa puhelinaika",

    //Booth Application Form
    "Apply.stall":"Hae näyttelystandia",
    "Apply.firstName":"Etunimi *",
    "Apply.lastName":"Sukunimi *",
    "Apply.nationality":"Kansallisuus *",
    "Apply.selectnationality":"Valitse kansallisuus *",
    "Apply.sweden":"Ruotsi",
    "Apply.denmark":"Tanska",
    "Apply.finland":"Suomi",
    "Apply.norway":"Norja",
    "Apply.other":"Muu",
    "Apply.emailaddress":"Sähköpostiosoite *",
    "Apply.fieldofcompany":"Yrityksen toimiala *",
    "Apply.rbooth":"Standi *",
    "Apply.selectbooth":"Valitse standi",
    "Apply.regularbooth":"Tavallinen standi - $5,500",
    "Apply.gold":"KULTA - $10,260",
    "Apply.platinum":"PLATINA - $15,390",
    "Apply.diamond":"TIMANTTI - $20,520",
    "Apply.organizationinfo":"Organisaation tiedot",
    "Apply.organizationname":"Organisaation nimi *",
    "Apply.organizationnumber":"Organisaationumero *",
    "Apply.mobile":"Matkapuhelin/Puhelin/Yhteysnumero *",
    "Apply.additionalinfo":"Lisätietoja (valinnainen)",
    "Apply.close":"Sulje",
    "Apply.submitapplication":"Lähetä hakemus",

    // Contact Section
    "Contact.title": "Ota yhteyttä",
    "Contact.title1": "Yhteystiedot",
    "Contact.text": "Virallinen pohjoismainen kumppani ICPM 2026:lle",
    "Contact.title3": "Sähköposti",
    "Contact.title4": "Verkkosivusto",
    "Contact.title5": "Lataa materiaaleja",
    "Contact.icpm": "ICPM 2026 -esite (PDF)",
    "Contact.floor": "Pohjapiirros (PDF)",

    "Contact.Sendtitle": "Lähetä meille viesti",
    "Contact.Sendname": "Nimi",
    "Contact.Sendcompany": "Yritys",
    "Contact.Sendemail": "Sähköposti",
    "Contact.Sendphone": "Puhelin",
    "Contact.Sendtext": "Olen kiinnostunut",
    "Contact.option1": "Osallistumisesta ICPM 2026 -näyttelyyn",
    "Contact.option2": "Sponsoroimismahdollisuuksista",
    "Contact.option3": "B2B-tapaamisista",
    "Contact.option4": "Muusta",
    "Contact.message": "Viesti",
    "Contact.sendmessage": "Lähetä viesti"
    
  },
  is: { 
     // Navigation
    "nav.about": "Um ICPM",
    "nav.why": "Af hverju UAE?",
    "nav.benefits": "Þátttaka",
    "nav.objective": "Markmið",
    "nav.future": "Framtíðaráætlun",
    "nav.booths": "Sýningastandavalkostir",
    "nav.contact": "Hafa samband",

    // Hero Section
    "hero.offer": "Einkarétt tilboð",
    "hero.companies": "Skandinavísk fyrirtæki fá 5% afslátt í gegnum Keeada!",
    "hero.contact": "Hafðu samband",
    "hero.claim": "til að nálgast afsláttinn þinn.",
    "hero.title": "Flytðu heilbrigðisframleiðslu þína til Mið-Austurlands",
    "hero.subtitle": "Sýndu á 14. ICPM-ráðstefnunni 2026 í UAE",
    "hero.text": "Vertu með á einni af stærstu heilbrigðis- og lyfjaframleiðslusýningum Mið-Austurlands.<br>20.-22. janúar 2026 — Sharjah Research Technology & Innovation Park, UAE.",
    "hero.apply": "Sækja um sýningapláss",
    "hero.download": "Sækja kynningarefni",
    "hero.call": "Panta símtal",
    "timer.title": "TÍMI EFTIR",
    "timer.days": "DAGA",
    "timer.hours": "KLST",
    "timer.minutes": "MÍN",
    "timer.seconds": "SEK",

    // About Section
    "about.title": "Hvað er ICPM?",
    "about.text1": "ICPM er vettvangur sem nær yfir innlenda og alþjóðlega markaði, þar sem þú færð einstaka tækifæri til að hitta lykilstjórnvöld og ákvarðanatökendur frá öllum GCC- og MENA-ríkjum og erlendis í heilbrigðisgeiranum.",
    "about.text2": "ICPM nær yfir læknisfræði, læknisfræðilegan ferðaþjónustu, tryggingar, lyfjafræðimenntun, lyfjaiðnað, regluvinnu, samsvararannsóknir, lyfjaeftirlit, lyfjaverðlagningu, tannlæknalaboratoríur, tannlækningar, greiningarlaboratoríur og GMP-deild, erfðafræði, dýralækningar, fagurfræði, húðsjúkdóma, fegurð og snyrtivörur, aðgengi og endurhæfingu.",
    "about.text3": "Þar að auki munt þú kynnast leiðandi iðnaðarsérfræðingum, ráðgjöfum, heilbrigðisþjónustuaðilum og forstjórum á heilbrigðissviði í einrúmi og B2B-fundum.",

    // Why UAE Section
    "why.title": "Af hverju UAE — og af hverju núna?",
    "why.text1": "Á hverju ári tengist ICPM við mismunandi árangursríkar sögur, og eftir árangur síðustu 13 viðburða í UAE, er ICPM í ár í samvinnu við stjórnvöld undir einum vettvangi.",
    "why.text2": "Stefna og framtíðarsýn UAE er að bæta og útvega heilbrigðisiðnað í heimsgæðum, stækka heilbrigðisumfang og vinna traust heilbrigðisyfirvalda og heilbrigðisþjónustuaðila.",
    "why.text3": "Hagkerfi UAE hefur orðið fyrir ófyrirséðri vöxt undanfarin ár sem eru afleiðing af stefnum sem eru hagstæð fyrir fjárfesta eins og að draga úr skrifræði og stækka hagkerfi og viðskipti í UAE. Með tilliti til mikilvægis þess og stuðnings sem veittur er af leiðtogum UAE, ákvað ICPM að nýta tækifærið og halda 14. útgáfu ICPM í UAE.",

    // Who Can Participate?
    "Who.title": "Hverjir geta tekið þátt?",
    "Who.text": "ICPM 2026 er kjörin fyrir fyrirtæki og stofnanir á eftirfarandi sviðum:",
    "Who.text1": "Lyfjaframleiðendur og líftækniiðnaður",
    "Who.text2": "Sjúkrahús og heilbrigðisþjónustuaðilar",
    "Who.text3": "Lækningabúnaðarfyrirtæki og dreifingaraðilar",
    "Who.text4": "Fyrirtæki sem framleiða einnota lækningabúnað og neysluvörur",
    "Who.text5": "Heilbrigðisráðgjafar og fjárfestar",
    "Who.text6": "Prófessorar frá lyfjafræði-/líftæknistofnunum",
    "Who.text7": "Háskólar og fræðimenn",
    "Who.text8": "Samlokunarfyrirtæki (sjúkrabílar, farsímasjúkrahús)",
    "Who.text9": "Heilbrigðistryggingafélög",
    "Who.text10": "Heilbrigðiserfðafræðicenter",
    "Who.text11": "Fagurfræði-, snyrtivöru- og fegurðarfyrirtæki",
    "Who.text12": "Heilbrigðisstofnanir stjórnvalda, fjölmiðlar og útgáfur",
    "Who.text13": "Ríkisstofnanir og sveitarfélög",
    "Who.text14": "Dýralæknavinna, fyrirtæki og dreifingaraðilar",
    "Who.text15": "Lyfjadreifingastofnanir og vísindastofur",
    "Who.text16": "Gisting, hótel, spa, endurhæfingarfyrirtæki",
    "Who.text17": "Óhagnaðarsamtök",
    "Who.text18": "Framleiðendur fjölvitamínna, lífrænna og jurtaafurða",
    "Who.text19": "Framleiðendur íþrótta- og næringarvara",
    "Who.text20": "Flutnings-, innflutnings- og útflutningsfyrirtæki",
    "Who.text21": "Frjálsviðskipastofnanir og geymsluaðstaða",

    // Purpose & Objectives of ICPM
    "Purpose.title": "Tilgangur og markmið ICPM",
    "Purpose.text1": "Að efla heilbrigðari lífsstíl og einnig að koma í veg fyrir lífsstílstengdar sjúkdóma.",
    "Purpose.text2": "Tengja fjölþjóðleg lyfja- og lækningafyrirtæki, dreifingaraðila og smásala við eftirlitsstofnanir UAE og GCC",
    "Purpose.text3": "Að varpa ljósi á meðvitund um lyfjameðferð fyrir fjöldasamkomur",
    "Purpose.text4": "Styrkja tengsl milli háskóla, framleiðenda, dreifingaraðila og smásala til hagsbóta fyrir heilbrigðisþjónustu",
    "Purpose.text5": "Efla, styðja og auðvelda læknisfræðilega ferðaþjónustu í UAE",
    "Purpose.text6": "Bjóða upp á heimsgæðameðferðir til lítillar kostnaðar",
    "Purpose.text7": "Sameina átök vísindastofnana og heilbrigðisfyrirtækja",
    "Purpose.text8": "Deila uppfærðri upplýsingum um nýjustu tækni",
    "Purpose.text9": "Efla nýjar viðskipta- og tækniíðróanir á heilbrigðissviði",
    "Purpose.text10": "Styrkja tengsl milli einkarekinnra og ríkisrekinnra sjúkrahúsa",
    "Purpose.text11": "Auka aðgengi að dreifðu heilbrigðiskerfi með því að koma á nýrri innviðauppbyggingu í núverandi stofnunum",
    "Purpose.text12": "Þróa innlendan lyfjaiðnað og sjúkrahús",

    // Future Plan
    "Future.title": "Framtíðaráætlun",
    "Future.text1": "Á hverju ári mun Keeada í gegnum ICPM vinna með ýmsum virtum heilbrigðisfyrirtækjum í UAE og um allan heim. Þar sem þetta verður tengiliður milli vísindamanna og fagfólks, munu allir ICPM-viðburðir okkar fara fram í samvinnu við virtustu fyrirtækin.",
    "Future.text2": "Þetta frumkvæði mun lyfta heilbrigðisgeiranum og skila bestu árangri frá heilbrigðisþjónustuaðilum sem móta framtíð læknisfræðinnar.",
    "Future.title1": "Alþjóðleg samvinna",
    "Future.text3": "Samstarf við leiðandi heilbrigðisstofnanir um allan heim",
    "Future.title2": "Stjórnvísi samstarf",
    "Future.text4": "Byggja brýr milli vísindamanna og atvinnufólks",
    "Future.title3": "Sjálfbær vöxtur",
    "Future.text5": "Skapa varanleg áhrif á nýsköpun á heilbrigðissviði",

    // Booth Options Section
    "Booth.title": "Sýningastandapakkningar og styrktaraðilakostir",
    "Booth.text": "Veldu þá stærð og sýnileikastig sem henta fyrirtækinu þínu best. Verð byrjar á 570 USD á fermetra. Afsláttur gæti átt við í gegnum Keeada.",
    "Booth.regular": "Venjulegur sýningastandur",
    "Booth.standard": "Staðlaður",
    "Booth.booth": "9 m² standur",
    "Booth.now": "Bóka núna",

    "Sponsorship.feature": "Eiginleikar",
    "Sponsorship.gold": "GULL",
    "Sponsorship.platinum": "PLATÍN",
    "Sponsorship.diamond": "DEMANTUR",

    "sponsorship.llist1": "Vörumerkjavæðing á staðnum",
    "sponsorship.llist2": "Matchmaking hvíldarstofa",
    "sponsorship.llist3": "Merki á vefsíðu ráðstefnunnar, kynningarefni, ICPM samfélagsmiðlum",
    "sponsorship.llist4": "Heimsókn stjórnvalda á standinn",
    "sponsorship.llist5": "Lýsing fyrirtækis á vefsíðu",
    "sponsorship.llist6": "Viðurkenning fyrirtækis á viðburði",
    "sponsorship.llist7": "Sýningarsvæði",
    "sponsorship.llist8": "Skipuleggja fund með stjórnvaldi",
    "sponsorship.llist9": "Skipuleggja fund við viðskiptafélaga",
    "sponsorship.llist10": "Kynning á viðburði",
    "sponsorship.llist11": "Ókeypis ráðgjöf frá ICPM",
    "sponsorship.llist12": "Ókeypis gisting",
    "sponsorship.llist13": "Ókeypis flutningur frá hóteli",
    "sponsorship.llist14": "Fundarborð á ráðstefnunni",
    "sponsorship.llist15": "Fyrirlestur í vísindaáætlun",

    "sponsorship.list1": "(+Skilti)",
    "sponsorship.list2": "(VIP-heimsókn)",
    "sponsorship.list3": "(Háttsettra heimsókn)",
    "sponsorship.list4": "150 orð",
    "sponsorship.list5": "200 orð",
    "sponsorship.list6": "250 orð",
    "sponsorship.list7": "(1. dagur)",
    "sponsorship.list8": "(Upphafshátíð)",
    "sponsorship.list9": "Góð staðsetning",
    "sponsorship.list10": "Hálf-ágætis",
    "sponsorship.list11": "Ágætis staða",
    "sponsorship.list12": "(Heilbrigðisþjónusta)",
    "sponsorship.list13": "(Heilbrigðisyfirvöld)",
    "sponsorship.list14": "1 herbergi",
    "sponsorship.list15": "2 herbergi",
    "sponsorship.list16": "3 herbergi",
    "sponsorship.list17": "(VIP borð)",
    "sponsorship.list18": "(VIP borð á viðburði)",

    "sponsorship.gbook": "Bóka núna",
    "sponsorship.pbook": "Bóka núna",
    "sponsorship.dbook": "Bóka núna",

    "sponsorship.location": "Sjá staðsetningu sýningastanda",
    "sponsorship.view": "Skoða skipulag",

    // Final CTA Section
    "Final.title": "Tilbúin(n) til að taka þátt í framtíð heilbrigðisþjónustu?",
    "Final.text": "Tryggðu þér pláss í dag og sýndu fram á nýjungar þínar á einum af mest sprengifimustu heilbrigðisviðburðum Mið-Austurlands.",
    "Final.apply": "Sækja um núna",
    "Final.book": "Panta símtal",

    //Booth Application Form
    "Apply.stall":"Sækja um sýningapláss",
    "Apply.firstName":"Fornafn *",
    "Apply.lastName":"Eftirnafn *",
    "Apply.nationality":"Þjóðerni *",
    "Apply.selectnationality":"Veldu þjóðerni *",
    "Apply.sweden":"Svíþjóð",
    "Apply.denmark":"Danmörk",
    "Apply.finland":"Finnland",
    "Apply.norway":"Noregur",
    "Apply.other":"Annað",
    "Apply.emailaddress":"Netfang *",
    "Apply.fieldofcompany":"Starfsemi fyrirtækis *",
    "Apply.rbooth":"Standur *",
    "Apply.selectbooth":"Veldu stand",
    "Apply.regularbooth":"Venjulegur standur - $5,500",
    "Apply.gold":"GULL - $10,260",
    "Apply.platinum":"PLATÍN - $15,390",
    "Apply.diamond":"DEMANTUR - $20,520",
    "Apply.organizationinfo":"Upplýsingar um stofnun",
    "Apply.organizationname":"Heiti stofnunar *",
    "Apply.organizationnumber":"Kennitala stofnunar *",
    "Apply.mobile":"Farsími/Sími/Sambandsnúmer *",
    "Apply.additionalinfo":"Viðbótarupplýsingar (Valfrjálst)",
    "Apply.close":"Loka",
    "Apply.submitapplication":"Senda inn umsókn",

    // Contact Section
    "Contact.title": "Hafðu samband",
    "Contact.title1": "Upplýsingar",
    "Contact.text": "Opinbert norrænt samstarfsaðili fyrir ICPM 2026",
    "Contact.title3": "Netfang",
    "Contact.title4": "Vefsíða",
    "Contact.title5": "Sækja úrræði",
    "Contact.icpm": "ICPM 2026 kynningarefni (PDF)",
    "Contact.floor": "Skipulag (PDF)",

    "Contact.Sendtitle": "Sendu okkur skilaboð",
    "Contact.Sendname": "Nafn",
    "Contact.Sendcompany": "Fyrirtæki",
    "Contact.Sendemail": "Netfang",
    "Contact.Sendphone": "Sími",
    "Contact.Sendtext": "Ég hef áhuga á",
    "Contact.option1": "Að sýna á ICPM 2026",
    "Contact.option2": "Styrktaraðilakostum",
    "Contact.option3": "B2B-fundum",
    "Contact.option4": "Öðru",
    "Contact.message": "Skilaboð",
    "Contact.sendmessage": "Senda skilaboð"
    
  }
};

// Function to change language
function setLanguage(lang) {
  // Update language selector display
  //document.getElementById('currentLanguage').textContent = lang === 'en' ? 'English' : 'Svenska';
  document.getElementById('currentLanguage').textContent =
    lang === 'en' ? 'English' :
    lang === 'sv' ? 'Svenska' :
    lang === 'no' ? 'Norsk' :
    lang === 'dk' ? 'Dansk' :
    lang === 'fi' ? 'Suomi' :
    lang === 'is' ? 'Íslenska' :
    lang;

  // Update HTML lang attribute
  document.documentElement.lang = lang;

  // Update all translatable elements
  document.querySelectorAll('[data-i18n]').forEach(element => {
    const key = element.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key]) {
      element.innerHTML = translations[lang][key];
    }
  });

  // Save preference to localStorage
  localStorage.setItem('preferredLanguage', lang);
}

// Initialize when page loads
document.addEventListener('DOMContentLoaded', () => {
  // Check for saved language or use browser default
  const savedLang = localStorage.getItem('preferredLanguage');
  const browserLang = navigator.language.startsWith('sv') ? 'sv' : 'en';
  const defaultLang = savedLang || browserLang;

  setLanguage(defaultLang);

  // Set up language switch buttons
  document.querySelectorAll('.language-btn').forEach(button => {
    button.addEventListener('click', (e) => {
      e.preventDefault();
      setLanguage(button.getAttribute('data-lang'));
    });
  });
});